import os
import json
import requests
import time
from github_bot.command_parser import parse_command
from ai_engine.router import generate
from ai_engine.prompt_builder import build_prompt
from backend.config import GITHUB_TOKEN

def process_events():
    """Process GitHub events from environment variables (GitHub Actions)."""
    event_path = os.getenv("GITHUB_EVENT_PATH")
    if not event_path:
        print("⚠️ GITHUB_EVENT_PATH not found. Skipping event processing.")
        return

    with open(event_path, "r") as f:
        event_data = json.load(f)

    # Check for issue_comment event
    if "comment" in event_data:
        comment_body = event_data["comment"]["body"]
        issue_url = event_data["issue"]["url"]
        repo_url = event_data["repository"]["url"]

        command, args = parse_command(comment_body)
        
        if command:
            print(f"🤖 AI Command detected: {command} with args: {args}")

            # Handle fix command autonomously
            if command == "fix" and "autonomous" in args.lower():
                print("⚡ Autonomous fix mode triggered.")
                response_text = handle_autonomous_fix(args, repo_url, event_data)
            else:
                prompt = build_prompt(command, args)
                response_text = generate(prompt)

            print(f"🤖 AI Response: {response_text}")
            post_comment(issue_url, response_text)
    else:
        print("ℹ️ No AI command detected in GitHub event.")

def handle_autonomous_fix(args, repo_url, event_data):
    """Placeholder for autonomous fix and PR creation logic."""
    # In a real environment, this would:
    # 1. Clone the repo
    # 2. Create a new branch
    # 3. Apply the AI-suggested fix
    # 4. Commit and push
    # 5. Open a Pull Request using the GitHub API

    # Simulate PR creation for demonstration
    pr_title = f"AI Autonomous Fix: {args[:50]}..."
    pr_body = f"This PR was automatically generated by AutoDevAI in response to the command: /ai fix {args}"

    return f"🚀 Autonomous mode triggered! I'm creating a new branch and opening a pull request with the fix: '{pr_title}'."

def post_comment(issue_url, message):
    """Post a comment back to a GitHub issue or PR."""
    if not GITHUB_TOKEN:
        print("⚠️ GITHUB_TOKEN not found. Cannot post comment.")
        return

    url = f"{issue_url}/comments"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {"body": message}

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        print(f"✅ Comment posted successfully.")
    except Exception as e:
        print(f"❌ Error posting comment: {e}")
